In [18]:
import pandas as pd

housing_csv = "housing_tr10.csv"
employment_csv = "employment_tr10.csv"
income_csv = "income_tr10.csv"
population_csv = "population_tr10.csv"

housing_df = pd.read_csv(housing_csv)
employment_df = pd.read_csv(employment_csv)
income_df = pd.read_csv(income_csv)
population_df = pd.read_csv(population_csv)

len(housing_df)

32095

In [24]:

housing_df_dc = housing_df.loc[(housing_df["ucounty"] == "District of Columbia") & (housing_df["end_date"] == "31DEC2016") & (housing_df["start_date"] == "01JAN2012")]

#housing_df_dc.tail()
#print(housing_df.count())
len(housing_df_dc)

178

In [25]:
housing_df_dc.head()

,timeframe,geo2010,NumOccupiedHsgUnits,NumOccupiedHsgUnits_m,geo2010_nf,start_date,end_date,PctSameHouse5YearsAgo,PctVacantHsgUnitsForRent,PctOwnerOccupiedHsgUnits,...,PctSubprimeConvOrigHomePur,forecl_ssl_1Kpcl_sf_condo,forecl_ssl_sf_condo,trustee_ssl_1Kpcl_sf_condo,trustee_ssl_sf_condo,PctAnnChgRMPriceSf_1yr,PctAnnChgRMPriceSf_5yr,PctAnnChgRMPriceSf_10yr,ucounty,indc
0,2012-16,DC Tract 1,2454,185,11001000100,01JAN2012,31DEC2016,.,9.3,52,...,X,X,X,X,X,X,X,X,District of Columbia,1
1,2012-16,DC Tract 2.01,3.0,4.0,11001000201,01JAN2012,31DEC2016,.,i,100,...,X,X,X,X,X,X,X,X,District of Columbia,1
2,2012-16,DC Tract 2.02,1585,146,11001000202,01JAN2012,31DEC2016,.,5.9,67,...,X,X,X,X,X,X,X,X,District of Columbia,1
3,2012-16,DC Tract 3,2544,124,11001000300,01JAN2012,31DEC2016,.,0.0,47,...,X,X,X,X,X,X,X,X,District of Columbia,1
4,2012-16,DC Tract 4,645,54,11001000400,01JAN2012,31DEC2016,.,7.7,65,...,X,X,X,X,X,X,X,X,District of Columbia,1

In [27]:
#employment_df
employment_df_dc = employment_df.loc[(employment_df["ucounty"] == "District of Columbia") & (employment_df["end_date"] == "31DEC2016") & (employment_df["start_date"] == "01JAN2012")]

#housing_df_dc.tail()
#print(housing_df.count())
len(employment_df_dc)

178

In [28]:
employment_df_dc.head()

,timeframe,geo2010,geo2010_nf,start_date,end_date,PctUnemployed,Pct16andOverEmployed,PctUnemployed_m,Pct16andOverEmployed_m,ucounty,indc
0,2012-16,DC Tract 1,11001000100,01JAN2012,31DEC2016,4.2,73,3.5,8.6,District of Columbia,1
1,2012-16,DC Tract 2.01,11001000201,01JAN2012,31DEC2016,6.6,41,5.9,8.7,District of Columbia,1
2,2012-16,DC Tract 2.02,11001000202,01JAN2012,31DEC2016,4.7,57,3.1,4.4,District of Columbia,1
3,2012-16,DC Tract 3,11001000300,01JAN2012,31DEC2016,2.1,80,2.4,5.8,District of Columbia,1
4,2012-16,DC Tract 4,11001000400,01JAN2012,31DEC2016,0.5,64,7.1,8.0,District of Columbia,1

In [30]:
income_df_dc = income_df.loc[(income_df["ucounty"] == "District of Columbia") & (income_df["end_date"] == "31DEC2016") & (income_df["start_date"] == "01JAN2012")]

#housing_df_dc.tail()
#print(housing_df.count())
len(income_df_dc)

178

In [31]:
income_df_dc.head()

,timeframe,geo2010,geo2010_nf,start_date,end_date,PctPoorPersons,PctPoorChildren,PctPoorElderly,AvgFamilyIncAdj,PctPoorPersons_m,PctPoorChildren_m,PctPoorElderly_m,AvgFamilyIncAdj_m,PctChgAvgFamilyIncAdj,Tanf_client,Fs_client,ucounty
0,2012-16,DC Tract 1,11001000100,01JAN2012,31DEC2016,3.3,0.0,2.3,401114,3.5,7.3,5.3,123212,X,X,X,District of Columbia
1,2012-16,DC Tract 2.01,11001000201,01JAN2012,31DEC2016,66,i,0.0,.,46,.,200,.,X,X,X,District of Columbia
2,2012-16,DC Tract 2.02,11001000202,01JAN2012,31DEC2016,21,3.2,3.6,275614,9.0,12,4.7,68928,X,X,X,District of Columbia
3,2012-16,DC Tract 3,11001000300,01JAN2012,31DEC2016,17,2.5,11,237089,7.8,8.4,11,60958,X,X,X,District of Columbia
4,2012-16,DC Tract 4,11001000400,01JAN2012,31DEC2016,10,8.4,2.8,486400,5.1,13,7.4,142495,X,X,X,District of Columbia

In [32]:
population_df_dc = population_df.loc[(population_df["ucounty"] == "District of Columbia") & (population_df["end_date"] == "31DEC2016") & (population_df["start_date"] == "01JAN2012")]

#housing_df_dc.tail()
#print(housing_df.count())
len(population_df_dc)

178

In [33]:
population_df_dc.head()

,timeframe,geo2010,TotPop,TotPop_m,geo2010_nf,start_date,end_date,PctPopUnder18Years,PctPop65andOverYears,PctForeignBorn,...,PctBlackNonHispBridge_m,PctWhiteNonHispBridge_m,PctHisp_m,PctAPINonHispBridge_m,PctFamiliesOwnChildFH_m,PctChgTotPop,PctChgPopUnder18Years,PctChgPop65andOverYear,ucounty,indc
0,2012-16,DC Tract 1,5005,401,11001000100,01JAN2012,31DEC2016,16,16,20,...,1.3,3.8,4.1,1.9,19,X,X,X,District of Columbia,1
1,2012-16,DC Tract 2.01,3733,361,11001000201,01JAN2012,31DEC2016,1.2,0.3,15,...,2.7,7.4,3.1,4.1,.,X,X,X,District of Columbia,1
2,2012-16,DC Tract 2.02,4417,556,11001000202,01JAN2012,31DEC2016,8.7,13,20,...,6.7,14,3.1,1.8,14,X,X,X,District of Columbia,1
3,2012-16,DC Tract 3,6139,632,11001000300,01JAN2012,31DEC2016,13,8.3,17,...,5.9,11,3.0,3.7,9.5,X,X,X,District of Columbia,1
4,2012-16,DC Tract 4,1607,159,11001000400,01JAN2012,31DEC2016,19,22,25,...,2.8,7.2,8.3,5.5,13,X,X,X,District of Columbia,1